"""
Extraction buffer writer.

Converts a populated ExtractionBuffer Pydantic model into the Markdown
format matching the existing manually-created buffers (e.g. MRLN-EXTRACTION-BUFFER.md).
"""
from __future__ import annotations

import json
from datetime import datetime
from pathlib import Path

from titanite.models.extraction_buffer import ExtractionBuffer


def _format_search_audit_table(buffer: ExtractionBuffer) -> str:
    """Render the Search Audit Trail Verification table."""
    extracts = buffer.transcript_extracts
    p1_count = len(extracts.pass_1_opportunities)
    p2_count = len(extracts.pass_2_red_flags)
    p3_count = len(extracts.pass_3_moat_concentration)

    p1_insight = (
        extracts.pass_1_opportunities[0].quote[:80] + "…"
        if extracts.pass_1_opportunities else "No signals extracted — requires manual review."
    )
    p2_insight = (
        extracts.pass_2_red_flags[0].quote[:80] + "…"
        if extracts.pass_2_red_flags else "No red flags detected."
    )
    p3_insight = (
        extracts.pass_3_moat_concentration[0].quote[:80] + "…"
        if extracts.pass_3_moat_concentration else "No moat signals extracted."
    )

    return f"""| Required Target Query Vector                    | Live Search Engine Query String Used | Total Results Clicked/Parsed | Primary Qualitative Insight Extracted |
| :---------------------------------------------- | :----------------------------------- | :--------------------------- | :------------------------------------ |
| **Pass 1:** Transcript Opportunities            | SEC EDGAR XBRL + automated keyword sweep | {p1_count} extracts | {p1_insight} |
| **Pass 2:** Transcript Red Flags                | SEC EDGAR XBRL + automated keyword sweep | {p2_count} extracts | {p2_insight} |
| **Pass 3:** Transcript Moats                    | SEC EDGAR XBRL + automated keyword sweep | {p3_count} extracts | {p3_insight} |
| **Step B:** Short Seller / Accounting Fraud     | _Requires manual web search_ | — | _Not yet automated — complete manually._ |
| **Step B:** Substack & Specialist Moat Analyses | _Requires manual web search_ | — | _Not yet automated — complete manually._ |
| **Step B:** National Innovation Agency Checks   | _Requires manual web search_ | — | _Not yet automated — complete manually._ |
| **Step B:** Executive / Leadership Background   | _Requires manual web search_ | — | _Not yet automated — complete manually._ |"""


def write_extraction_buffer(buffer: ExtractionBuffer, output_path: Path) -> None:
    """
    Write a populated ExtractionBuffer to a .md file at output_path.

    The output format exactly matches the existing MRLN-EXTRACTION-BUFFER.md
    structure so it can be read and audited using the same workflow.
    """
    output_path.parent.mkdir(parents=True, exist_ok=True)

    ticker = buffer.ticker.upper()
    date_str = buffer.audit_completed_at
    generated_at = datetime.now().strftime("%Y-%m-%d %H:%M UTC")

    audit_table = _format_search_audit_table(buffer)

    # Serialise the buffer to JSON, preserving all fields
    buffer_json = buffer.model_dump(mode="json")
    json_str = json.dumps(buffer_json, indent=2)

    content = f"""# CHOKEPOINT RESEARCH REPORT — DATA EXTRACTOR (TURN 1)

### Deep AI supply chain bottleneck analysis — Stock: {ticker}

> **Auto-generated by Titanite Pipeline** on {generated_at}
> Framework version: v2.0.0
> SEC EDGAR data as of: {date_str}
>
> **IMPORTANT — Steps requiring manual completion:**
> - Step B (short seller / fraud / moat analysis) requires live web searches
> - Backlog figures (`stated_backlog_firm_binding_usd`) must be sourced from earnings transcripts
> - `projected_12m_backlog_drawdown_velocity_usd` must be set from management guidance
> - `operational_flags` should be reviewed and overridden where automated detection is insufficient
> - All scores remain unset until manual scorer pass (Turn 2)

---

## RAW DATA EXTRACTION BUFFER

## SEARCH AUDIT TRAIL VERIFICATION (MANDATORY)

Before writing out the JSON code block, you must populate this exact Search Execution Log. If any row is marked as skipped or left unexecuted, the entire run is invalid.

{audit_table}

```json
{json_str}
```
"""

    output_path.write_text(content, encoding="utf-8")


def read_extraction_buffer(buffer_path: Path) -> ExtractionBuffer:
    """
    Parse an existing EXTRACTION-BUFFER.md file back into an ExtractionBuffer model.

    Extracts the JSON code block from the markdown file.
    """
    content = buffer_path.read_text(encoding="utf-8")

    # Find the JSON code block
    start_marker = "```json"
    end_marker = "```"

    start_idx = content.find(start_marker)
    if start_idx == -1:
        raise ValueError(f"No JSON code block found in {buffer_path}")

    json_start = start_idx + len(start_marker)
    end_idx = content.find(end_marker, json_start)
    if end_idx == -1:
        raise ValueError(f"Unclosed JSON code block in {buffer_path}")

    json_str = content[json_start:end_idx].strip()
    data = json.loads(json_str)
    return ExtractionBuffer.model_validate(data)
