'use client';

/**
 * useResearchCompanies — client-side hook to fetch the scored research universe.
 *
 * Sourced from: public/research-data/companies.json (generated by `titanite export`).
 * If NEXT_PUBLIC_USE_MOCK_DATA=true, it resolves with the static mock universe.
 */

import { useQuery } from '@tanstack/react-query';
import type { CompaniesPayload } from '@/types/research';

const MOCK_COMPANIES = [
  { ticker: 'PENG', companyName: 'Penguin Solutions, Inc.', score: 13, tier: 'Tier 1' as const, industryFolder: 'AI-CLOUD-INFRA', keySummary: 'AI liquid cooling + managed services for hyperscalers', framework: 'sc' as const },
  { ticker: 'ACCON', companyName: 'Acconeer AB', score: 13, tier: 'Tier 1' as const, industryFolder: 'robotics', keySummary: 'Pulsed coherent radar for humanoid robot perception', framework: 'sc' as const },
  { ticker: 'SHT', companyName: 'Smart High-Tech AB', score: 13, tier: 'Tier 1' as const, industryFolder: 'Semis', keySummary: 'Specialised PCB assemblies for AI/robotics', framework: 'sc' as const },
  { ticker: 'TLN', companyName: 'Talen Energy Corporation', score: 13, tier: 'Tier 1' as const, industryFolder: 'ENERGY', keySummary: 'Nuclear + data centre colocation (Susquehanna)', framework: 'sc' as const },
  { ticker: 'AAOI', companyName: 'Applied Optoelectronics, Inc.', score: 12, tier: 'Tier 1' as const, industryFolder: 'photonics', keySummary: '800G QSFP transceivers for hyperscaler AI clusters', framework: 'sc' as const },
  { ticker: 'MRLN', companyName: 'Marlin Technologies', score: 11, tier: 'Tier 2' as const, industryFolder: 'robotics', keySummary: 'Autonomous mobile robot fleet management software', framework: 'sc' as const },
  { ticker: 'IQE', companyName: 'IQE plc', score: 11, tier: 'Tier 2' as const, industryFolder: 'photonics', keySummary: 'Epitaxial wafer supplier for photonic chips', framework: 'sc' as const },
];

export function useResearchCompanies() {
  return useQuery<CompaniesPayload>({
    queryKey: ['research-companies'],
    queryFn: async () => {
      if (process.env.NEXT_PUBLIC_USE_MOCK_DATA === 'true') {
        return {
          exportedAt: new Date().toISOString(),
          count: MOCK_COMPANIES.length,
          companies: MOCK_COMPANIES,
        };
      }
      const res = await fetch('/research-data/companies.json');
      if (!res.ok) {
        throw new Error(`Companies JSON fetch failed: ${res.status}`);
      }
      return res.json() as Promise<CompaniesPayload>;
    },
    staleTime: 300000, // Cache for 5 minutes
  });
}
