/**
 * Research service — reads Titanite JSON exports for the Next.js frontend.
 *
 * Architecture rules (from AGENTS.md):
 * - All API/data calls go through src/lib/services/. Never raw fetch in components.
 * - NEXT_PUBLIC_USE_MOCK_DATA=true uses mock data; false reads from public/research-data/.
 * - This service is server-side only (reads filesystem JSON, not a remote API).
 *
 * Data source: public/research-data/*.json — generated by `titanite export`
 * To refresh data: cd research/titanite-app && titanite export
 */

import type {
  ResearchedCompany,
  ResearchCatalyst,
  CompaniesPayload,
  CatalystsPayload,
  HoldingsPayload,
} from '@/types/research';

const USE_MOCK = process.env.NEXT_PUBLIC_USE_MOCK_DATA === 'true';

// ---------------------------------------------------------------------------
// Data fetchers — server-side only (no 'use client' in callers)
// ---------------------------------------------------------------------------

async function fetchResearchJson<T>(filename: string): Promise<T> {
  // Server-side: read directly from the filesystem (public/ dir)
  // This works during next build, SSR, and ISR without needing a running server.
  if (typeof window === 'undefined') {
    const { readFileSync } = await import('fs');
    const { join } = await import('path');
    const filePath = join(process.cwd(), 'public', 'research-data', filename);
    try {
      const raw = readFileSync(filePath, 'utf-8');
      return JSON.parse(raw) as T;
    } catch {
      throw new Error(
        `Could not read ${filePath}. ` +
        `Run 'titanite export' to generate research-data/ JSON files.`
      );
    }
  }

  // Client-side fallback (shouldn't be reached — this service is server-only)
  const res = await fetch(`/research-data/${filename}`, {
    next: { revalidate: 300 },
  });
  if (!res.ok) {
    throw new Error(`Failed to fetch ${filename}: ${res.status}`);
  }
  return res.json() as Promise<T>;
}

// ---------------------------------------------------------------------------
// Mock data (used when NEXT_PUBLIC_USE_MOCK_DATA=true)
// ---------------------------------------------------------------------------

const MOCK_COMPANIES: ResearchedCompany[] = [
  { ticker: 'PENG', companyName: 'Penguin Solutions, Inc.', score: 13, tier: 'Tier 1', industryFolder: 'AI-CLOUD-INFRA', keySummary: 'AI liquid cooling + managed services for hyperscalers', framework: 'sc' },
  { ticker: 'ACCON', companyName: 'Acconeer AB', score: 13, tier: 'Tier 1', industryFolder: 'robotics', keySummary: 'Pulsed coherent radar for humanoid robot perception', framework: 'sc' },
  { ticker: 'SHT', companyName: 'Smart High-Tech AB', score: 13, tier: 'Tier 1', industryFolder: 'Semis', keySummary: 'Specialised PCB assemblies for AI/robotics', framework: 'sc' },
  { ticker: 'TLN', companyName: 'Talen Energy Corporation', score: 13, tier: 'Tier 1', industryFolder: 'ENERGY', keySummary: 'Nuclear + data centre colocation (Susquehanna)', framework: 'sc' },
  { ticker: 'AAOI', companyName: 'Applied Optoelectronics, Inc.', score: 12, tier: 'Tier 1', industryFolder: 'photonics', keySummary: '800G QSFP transceivers for hyperscaler AI clusters', framework: 'sc' },
  { ticker: 'MRLN', companyName: 'Marlin Technologies', score: 11, tier: 'Tier 2', industryFolder: 'robotics', keySummary: 'Autonomous mobile robot fleet management software', framework: 'sc' },
  { ticker: 'IQE', companyName: 'IQE plc', score: 11, tier: 'Tier 2', industryFolder: 'photonics', keySummary: 'Epitaxial wafer supplier for photonic chips', framework: 'sc' },
];

const MOCK_CATALYSTS: ResearchCatalyst[] = [
  { ticker: 'ACCON', description: 'Commercial ramp / Series C design win', expectedDate: 'Q3 2026 (July-Sept)', confidence: 'High', status: 'active', thesisImpact: 'Validates humanoid perception thesis', actualDate: null, deltaDays: null },
  { ticker: 'TLN', description: 'Hyperscale data centre colocation deal announcement', expectedDate: 'Q2 2026', confidence: 'High', status: 'active', thesisImpact: 'De-risks nuclear energy revenue model', actualDate: null, deltaDays: null },
  { ticker: 'AAOI', description: '800G volume ramp with top-3 hyperscaler', expectedDate: 'H2 2026', confidence: 'Medium-High', status: 'active', thesisImpact: 'Revenue inflection point', actualDate: null, deltaDays: null },
];

// ---------------------------------------------------------------------------
// Public API
// ---------------------------------------------------------------------------

/** Fetch all researched companies. Sorted by score descending. */
export async function getResearchedCompanies(): Promise<ResearchedCompany[]> {
  if (USE_MOCK) {
    return MOCK_COMPANIES.sort((a, b) => b.score - a.score);
  }

  const payload = await fetchResearchJson<CompaniesPayload>('companies.json');
  return payload.companies.sort((a, b) => b.score - a.score);
}

/** Fetch active catalysts only, sorted by ticker. */
export async function getActiveCatalysts(): Promise<ResearchCatalyst[]> {
  if (USE_MOCK) {
    return MOCK_CATALYSTS;
  }

  const payload = await fetchResearchJson<CatalystsPayload>('catalysts.json');
  return payload.catalysts.filter((c) => c.status === 'active');
}

/** Fetch current Titanite holdings (subset of companies currently held). */
export async function getResearchHoldings(): Promise<ResearchedCompany[]> {
  if (USE_MOCK) {
    return MOCK_COMPANIES.filter((c) => ['PENG', 'ACCON', 'AAOI', 'TLN'].includes(c.ticker));
  }

  const payload = await fetchResearchJson<HoldingsPayload>('holdings.json');
  return payload.holdings;
}

/**
 * Build a lookup map from ticker → ResearchedCompany.
 * Used to enrich T212 holdings with Titanite scores.
 */
export function buildResearchLookup(
  companies: ResearchedCompany[]
): Map<string, ResearchedCompany> {
  return new Map(companies.map((c) => [c.ticker.toUpperCase(), c]));
}

/** Get the export timestamp from the companies payload. */
export async function getResearchExportedAt(): Promise<string | null> {
  if (USE_MOCK) return new Date().toISOString();
  try {
    const payload = await fetchResearchJson<CompaniesPayload>('companies.json');
    return payload.exportedAt;
  } catch {
    return null;
  }
}
